### PR TITLE
Dashboard Material you compatible

### PR DESCRIPTION
**Pull request by yogeshpaliyal**
@Gurupreet Please have a look

- Dashboard all tabs UI compatible with Material You

### CODE REVIEW

**Review by Gurupreet — APPROVED** [review]

**Comment by Gurupreet** [comment]
Can you check tests I think CI was working recently.

**Comment by Gurupreet** [comment]
Great work regardless I guess we are almost there with Material3

**Comment by yogeshpaliyal** [comment]
> Can you check tests I think CI was working recently.

Yes, sure. I will fix this tomorrow

**Comment by yogeshpaliyal** [comment]
> Great work regardless I guess we are almost there with Material3 

Yes, almost. Do we have to change the demo apps ui as well?

**Comment by yogeshpaliyal** [comment]
> Can you check tests I think CI was working recently.

@Gurupreet the test cases failed due to Material 3 buttons, `hasClickAction()` this return `false` for material 3 buttons and true for Material 2 Buttons

**Comment by Gurupreet** [comment]
Hmm interesting find let me check on it @yogeshpaliyal 👍🏽

**Pull request merged**
