### PR TITLE
refactor: Migrate instagram in a Gradle module.

### PR DESCRIPTION
**Pull request by GerardPaligot**
# Motivation

Suggest a first implementation for multi module strategy for demo apps.

# Changelog

- Create :data module for fake data provider.
- Create :theme module for all compose template resources.
- Create :demos:instagram module for instagram demo app.

Issue #61

### CODE REVIEW

**Comment by GerardPaligot** [comment]
@Gurupreet Android build fixed here. `ic_baseline_home_24` used `colorControlNormal` attribute in tint property but this icon is never used and (I think) this attribute shouldn't be used on the definition of the icon. I just removed the property. Hope it is ok.

**Review by hfrsoussama — APPROVED** [review]
Thanks @GerardPaligot 👍

**Comment by Gurupreet** [comment]
Thanks @GerardPaligot great work :)

**Comment by GerardPaligot** [comment]
Happy the structure is okay for you. I'll migrate others demos with the same structure in next days! :)

**Comment by Gurupreet** [comment]
Yes it's great and cleaner. Would be really nice if CryptoApp one and MovieApp one can be separated standalone module as they have MVVM/APIS etc with them 💯

**Comment by GerardPaligot** [comment]
challenge-accepted-barney-5619

**Pull request merged**
