### PR TITLE
update constraintLayoutCompose to beta02

### PR DESCRIPTION
**Pull request by wiryadev**

### CODE REVIEW

**Review by Gurupreet — APPROVED** [review]

**Comment by Gurupreet** [comment]
There are some issues with navigation compose alpha05. Let me know if you faced it anywhere in Gmail or Tiktok demo.

**Comment by wiryadev** [comment]
> There are some issues with navigation compose alpha05. Let me know if you faced it anywhere in Gmail or Tiktok demo.

what kind of issue? if it is related to crossfade effect, that because alpha05 kind of force-enable crossfade effect when navigating

image

**Comment by Gurupreet** [comment]
https://twitter.com/hi_man_shoe/status/1421839886122819590?s=20
Not necessarily happening in all.

**Comment by wiryadev** [comment]
> https://twitter.com/hi_man_shoe/status/1421839886122819590?s=20
> Not necessarily happening in all.

i think we should just wait for the [update](https://issuetracker.google.com/issues/194301889)
image

**Comment by wiryadev** [comment]
i try it out and didnt find anything weird on tiktok and gmail demo. Still, could be i just didnt notice it.

**Pull request merged**
